# Generated by Django 2.1.2 on 2018-10-25 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=12, unique=True)),
                ('correo', models.CharField(max_length=60)),
                ('nombre_completo', models.CharField(max_length=60)),
                ('f_nacimiento', models.DateField()),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ciudad', models.IntegerField(unique=True)),
                ('ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_region', models.IntegerField(unique=True)),
                ('region', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vivienda', models.IntegerField(unique=True)),
                ('vivienda', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Region'),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ciudad'),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Region'),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='vivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Vivienda'),
        ),
    ]
